### ISSUE TITLE
Launcher is mandatory and it doesn't work (it needs Mono)

### ISSUE THREAD

**Issue by hunter440p** [zeroz41/pso_wine#1]
Hello,
I tried to install pso, installation is OK but it doesn't launch.
If you use the "Ephinea PSOBB" shortcut, game start but it can't connect to the server (error : not the latest client version)
It need to use the "Ephinea Launcher" to work (launcher is mandatory).

To execute the launcher, I tried to use this command : 
python pso.py -el

But error : 
"0024:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed"

To get it works : 
- I download this https://dl.winehq.org/wine/wine-mono/9.3.0/wine-mono-9.3.0-x86.msi
- I used this command :  
WINEPREFIX=~/.local/share/ephinea-prefix wine uninstaller
- In the window opened, I selected the wine-mono-9.3.0-x86.msi to install it and click on OK

After this, when I used again the command to open the launch : 
python pso.py -el
=> It works

If I use the shortcut "Ephinea Launcher", it works.

**Is there a way to add Mono installation in your script ?**

Thanks

**Comment by zeroz41** [comment]
It looks like wine-mono is available via package managers for a lot of distros, and 'should' often satisfy the mono requirement for system wine. 
I can attempt to check if a suitable wine-mono is present on desktop installation, and if not, download and install msi wine prefix only version directly into pso prefix (not system wide).

**Comment by zeroz41** [comment]
Complete and merged. Wine gecko support as well. Reopen if any future issues.

**Comment by hunter440p** [comment]
Thanks !
I tested on a fresh installation of linux mint, worked perfectly ! :)

**Comment by zeroz41** [comment]
@hunter440p good to hear :)
